name: Update oc.pyos

on:
  repository_dispatch:
    types: dispatch-from-pyos
  push:
    branches:
      - main
env:
    imagetag: dev
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:   
      - uses: actions/checkout@v3
        with:
          ref: main
          
      - name: clone pyos main branch    
        run: |
          cd var
          git clone https://github.com/abcdesktopio/pyos
          
      - name: dump-github-event-client_payload
        run: echo ${{ github.event.client_payload.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
         
      - name: "image tag with branch if set"
        if: ${{ github.event.client_payload }}
        run: echo "${{ github.event.client_payload }}"
        env:
          imagetag: github.event.client_payload

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: .
          file: oc.pyos
          push: true
          tags: |
            abcdesktopio/oc.pyos:${{ env.imagetag }}
            
      # - name: update platform
      #  run: curl -X POST -u "${{ secrets.WEBHOOK_USERNAME }}:${{ secrets.WEBHOOK_PASSWORD }}" -d "daemonset-pyos"  "${{ secrets.WEBHOOK_URL }}/kubernetes/rollout"
      
